/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/*Base Addres for Clock control block*/
#define RCC_BASE 0x40021000U
/*Register address that controls the difference hardware blocks*/
#define RCC_AHB2ENR (*(volatile uint32_t*)(RCC_BASE + 0x4CU))
/*Base Address for GPIOs*/
#define GPIOA_BASE 0x48000000U
#define GPIOB_BASE 0x48000400U
/*Register address that controls the GPIO*/
#define GPIOA_MODER (*(volatile uint32_t*)(GPIOA_BASE + 0x00))
#define GPIOA_BSRR (*(volatile uint32_t*)(GPIOA_BASE + 0x18))
#define GPIOB_MODER (*(volatile uint32_t*)(GPIOB_BASE + 0x00))
#define GPIOB_BSRR (*(volatile uint32_t*)(GPIOB_BASE + 0x18))

/*Main function control the registers and the GPIOS Bare metal style*/
int main(void)
{
    // Enable GPIOB clock
    RCC_AHB2ENR |= (1U << 1);

    // Clear PB3 mode bits
    GPIOB_MODER &= ~(0x3U << 6);
    // Set PB3 as output
    GPIOB_MODER |=  (0x1U << 6);

    // Set PB3 HIGH - turn LED on
    // GPIOB_BSRR |= (1U << 3);
    while(1)
    {
		for(uint32_t i = 0; i<= 100000; i++)
		{
			GPIOB_BSRR |= (1U << 3);
		}

		for(uint32_t i = 0; i<= 100000; i++)
		{
			GPIOB_BSRR |= (1U << 19);
		}
    }
}
